// Catálogo de personas usadas na homologação assistida.
export const personas = [
  {
    id: 'cliente-novo',
    port: 7811,
    mobile: false,
    nome: 'Marina Costa',
    login: 'marina@demo.local',
    perfil: 'Cliente de primeira viagem, 29 anos, nunca agendou corte online. Usa o site no notebook. Tem pressa e pouca paciência com formulário confuso.',
    missao: [
      'Entrar como cliente e entender, só olhando a tela, o que a barbearia oferece e quanto custa.',
      'Agendar "Corte assinatura" com o Rafael Navalha para um dia útil futuro, dentro do horário de atendimento (09:00 às 20:00).',
      'Ao cair na tela do Mercado Pago (simulada), pagar o sinal e voltar para o app.',
      'Conferir se o agendamento aparece na sua agenda com o pagamento reconhecido.',
    ],
  },
  {
    id: 'cliente-mobile',
    port: 7812,
    mobile: true,
    nome: 'Pedro Lima',
    login: 'pedro@demo.local',
    perfil: 'Cliente recorrente, agenda sempre pelo celular no intervalo do trabalho. Viewport 390x844. Odeia rolar demais e botão pequeno.',
    missao: [
      'Entrar pelo celular e agendar "Corte + barba" com quem tiver horário livre.',
      'Avaliar a experiência mobile: o que fica cortado, apertado, exige zoom ou rolagem excessiva.',
      'Concluir o pagamento do sinal na tela simulada do Mercado Pago.',
      'Verificar se dá para ver claramente o próximo horário logo ao abrir o app.',
    ],
  },
  {
    id: 'cliente-cancelamento',
    port: 7813,
    mobile: false,
    nome: 'Lucas Rocha',
    login: 'lucas@demo.local',
    perfil: 'Cliente desorganizado que sempre precisa remarcar. Quer saber se perde o dinheiro do sinal ao cancelar.',
    missao: [
      'Tentar agendar num horário FORA do expediente (por exemplo 07:00 ou 23:00) e num domingo, e julgar se a mensagem de erro explica bem o problema.',
      'Tentar agendar num horário já ocupado pelo mesmo barbeiro e avaliar a mensagem de conflito.',
      'Fazer um agendamento válido, pagar o sinal e depois cancelar.',
      'Julgar se o app deixa claro o que acontece com o dinheiro do sinal ao cancelar e se existe opção de remarcar.',
    ],
  },
  {
    id: 'barbeiro-dono',
    port: 7814,
    mobile: false,
    nome: 'Rafael Navalha',
    login: 'rafael@demo.local',
    perfil: 'Dono da barbearia, 38 anos, corta cabelo o dia inteiro e usa o sistema entre um cliente e outro. Quer saber quanto entrou hoje sem fazer conta.',
    missao: [
      'Entrar como barbeiro dono e avaliar se o painel responde de imediato: quantos clientes hoje, quanto vou receber, quem é o próximo.',
      'Confirmar um agendamento pendente e concluir outro.',
      'Cadastrar um serviço novo ("Pezinho", 15 min, R$ 20) e tentar excluir um serviço que tem agendamento ativo.',
      'Abrir as configurações da barbearia, mudar cor/endereço/horários e salvar.',
      'Avaliar a área de assinatura mensal (R$ 20) e a conexão com o Mercado Pago: dá para entender o que é cobrado e a comissão de 1%?',
    ],
  },
  {
    id: 'barbeiro-funcionario',
    port: 7815,
    mobile: true,
    nome: 'Caio Santos',
    login: 'caio@demo.local',
    perfil: 'Barbeiro contratado (não é dono). Usa o celular entre atendimentos. Só quer ver a agenda dele e marcar como concluído.',
    missao: [
      'Entrar como barbeiro funcionário pelo celular e ver a agenda do dia.',
      'Confirmar e concluir atendimentos.',
      'Tentar acessar as configurações da barbearia e a assinatura: avaliar se o app deixa claro o que ele pode e o que não pode fazer, ou se apenas mostra erro.',
      'Avaliar se a tela ajuda no dia a dia entre atendimentos (informação essencial visível sem rolar).',
    ],
  },
]
